"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {Application,blankApplication,statuses,accountRequest} from "@/lib/workspace";
type Event={id:string;event_type:string;old_value:string;new_value:string;note:string;created_at:string};
export default function Tracker(){
 const [items,setItems]=useState<Application[]>([]),[edit,setEdit]=useState<Application|null>(null),[filter,setFilter]=useState('all'),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[events,setEvents]=useState<Event[]>([]),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{let active=true;accountRequest('me').then(()=>{if(active)setSignedIn(true);return accountRequest('applications')}).then(data=>{if(active)setItems(data.applications)}).catch(e=>{if(active)setMessage(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!edit)return;setSaving(true);setMessage('');try{await accountRequest(`applications${edit.id?'/'+edit.id:''}`,{method:edit.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});setItems((await accountRequest('applications')).applications);setEdit(null);setMessage('Application saved.')}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 async function remove(id:string){setSaving(true);try{await accountRequest('applications/'+id,{method:'DELETE'});setItems(items.filter(i=>i.id!==id));setEdit(null);setMessage('Application deleted.')}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 function select(item:Application){setEdit(item);setEvents([]);if(item.id)accountRequest(`applications/${item.id}/events`).then(d=>setEvents(d.events)).catch(()=>{})}
 const today=new Date().toISOString().slice(0,10);const due=items.filter(i=>i.status==='started'&&i.reminder_date&&i.reminder_date<=today&&(!i.deadline||i.deadline>=today));
 const filtered=items.filter(i=>filter==='all'||i.status===filter);
 return <><Header/><main id="main-content" className="shell workspace-page"><div className="workspace-heading"><div><p className="eyebrow">YOUR JOB HUNT, ORGANISED</p><h1>Application tracker</h1><p>Save the details. Confirm when you apply. Keep track of each response.</p></div>{signedIn&&<button className="btn-primary" onClick={()=>{setEdit({...blankApplication});setEvents([])}}>Add application +</button>}</div>
 <nav className="workspace-tabs"><Link href="/search">Find opportunities</Link><Link href="/tracker" aria-current="page">Applications</Link><Link href="/cv">CV studio</Link></nav>
 {message&&<p role="status" className="source-warning">{message}</p>}{loading?<p>Loading your applications…</p>:!signedIn?<section className="empty-state"><h2>Your private workspace starts with an account.</h2><Link href="/login" className="btn-primary">Log in</Link> <Link href="/signup" className="btn-outline">Create account</Link></section>:<>
 {due.length>0&&<section className="reminder-panel"><h2>Deadline reminders</h2>{due.map(i=><button key={i.id} className="reminder-item" onClick={()=>select(i)}>{i.job_title} at {i.company_name} <span>{i.deadline?`Deadline: ${i.deadline}`:'Your chosen reminder is due'}</span></button>)}</section>}
 <div className="tracker-stats"><div><strong>{items.length}</strong><span>Total records</span></div><div><strong>{items.filter(i=>i.status==='applied').length}</strong><span>Applied</span></div><div><strong>{items.filter(i=>i.status==='interview').length}</strong><span>Interviews</span></div><div><strong>{items.filter(i=>i.status==='offer').length}</strong><span>Offers</span></div></div>
 <label className="field-label" htmlFor="status-filter">Filter by status</label><select id="status-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All applications</option>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select>
 <div className="application-list">{filtered.map(item=><button className="application-row" key={item.id} onClick={()=>select(item)}><span><strong>{item.job_title}</strong><small>{item.company_name} · {item.location||'Location not supplied'}</small></span><span className={'status-badge '+item.status}>{item.status}</span><span>{item.date_applied||'Not confirmed applied'}<small>{item.reminder_date?`Reminder ${item.reminder_date}`:'No reminder set'}</small></span><span aria-hidden="true">↗</span></button>)}{filtered.length===0&&<div className="empty-state"><h2>No applications here yet.</h2><p>Add one manually or save a role from its details page.</p><Link href="/search" className="btn-outline">Search jobs</Link></div>}</div>
 {edit&&<section className="application-editor"><div className="editor-heading"><h2>{edit.id?'Application details':'Add an application'}</h2><button className="btn-outline" onClick={()=>setEdit(null)}>Close</button></div><form onSubmit={save}><div className="editor-grid">{([['job_title','Job title'],['company_name','Company name'],['company_website','Company website'],['location','Location'],['source_url','Application source URL'],['source','Source'],['contact_person','Contact person'],['salary_currency','Salary currency'],['salary_period','Salary period']] as const).map(([key,label])=><label key={key}>{label}<input value={edit[key]} required={key==='job_title'||key==='company_name'} type={key==='source_url'||key==='company_website'?'url':'text'} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}
 <label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value,date_applied:e.target.value==='applied'?(edit.date_applied||today):edit.date_applied})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>{(['date_applied','deadline','reminder_date'] as const).map(key=><label key={key}>{key.replaceAll('_',' ')}<input type="date" value={edit[key]||''} onChange={e=>setEdit({...edit,[key]:e.target.value||null})}/></label>)}{(['salary_min','salary_max'] as const).map(key=><label key={key}>{key.replaceAll('_',' ')}<input type="number" min="0" value={edit[key]??''} onChange={e=>setEdit({...edit,[key]:e.target.value?Number(e.target.value):null})}/></label>)}</div>
 <label>Notes<textarea rows={5} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={edit.email_reminder} onChange={e=>setEdit({...edit,email_reminder:e.target.checked})}/>Also email me a deadline reminder</label><p className="field-help">A known deadline sets a reminder two days earlier. Without a deadline, choose your own date. Started means you opened or saved a role, not that you submitted it.</p><div className="editor-actions"><button disabled={saving} className="btn-primary">{saving?'Saving…':'Save changes'}</button>{edit.id&&<button disabled={saving} type="button" className="btn-outline danger" onClick={()=>remove(edit.id!)}>Delete application</button>}</div></form>{events.length>0&&<div className="application-timeline"><h3>Activity</h3>{events.map(e=><p key={e.id}><time>{new Date(e.created_at).toLocaleDateString()}</time> {e.event_type.replaceAll('_',' ')} {e.new_value}{e.note&&<span>{e.note}</span>}</p>)}</div>}</section>}
 </> }</main><Footer/></>
}
