"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {accountRequest} from "@/lib/workspace";
type Match={matched:string[];missing:string[];unassessed:string;mode:string};
export default function CVStudio(){
 const [signedIn,setSignedIn]=useState(false),[loading,setLoading]=useState(true),[text,setText]=useState(''),[description,setDescription]=useState(''),[title,setTitle]=useState(''),[company,setCompany]=useState(''),[confirmed,setConfirmed]=useState(false),[saveProfile,setSaveProfile]=useState(false),[output,setOutput]=useState(''),[match,setMatch]=useState<Match|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;accountRequest('me').then(()=>{if(!active)return;setSignedIn(true);const job=sessionStorage.getItem('zag-cv-job');if(job){try{const j=JSON.parse(job);setDescription(j.description||'');setTitle(j.title||'');setCompany(j.company||'')}catch{}sessionStorage.removeItem('zag-cv-job')}return accountRequest('profile')}).then(d=>{if(active&&d)setText(d.verified_text||'')}).catch(e=>{if(active)setMessage(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function upload(file:File){setBusy(true);setMessage('');try{const body=new FormData();body.append('file',file);const data=await accountRequest('cv/extract',{method:'POST',body});setText(data.text);setConfirmed(false);setOutput('');setMessage(data.message)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function generate(letter=false){setBusy(true);setMessage('');try{const payload={verified_text:text,job_description:description,job_title:title,company_name:company,confirmed};const data=await accountRequest(letter?'cv/cover-letter':'cv/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setOutput(data.document);setMatch(letter?null:data);setMessage(data.message||data.mode);if(saveProfile)await accountRequest('profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({verified_text:text})})}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function download(format:'pdf'|'docx'){setBusy(true);try{const r=await fetch('/api/account/cv/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:output,title:'Career document',format})});if(!r.ok)throw new Error('Could not export this document.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`zagjobsearch-document.${format}`;a.click();URL.revokeObjectURL(url)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><Header/><main id="main-content" className="shell workspace-page"><div className="workspace-heading"><div><p className="eyebrow">YOUR EXPERIENCE, PRESENTED CLEARLY</p><h1>CV studio</h1><p>Upload your CV, review its facts, and tailor the evidence to a role.</p></div></div><nav className="workspace-tabs"><Link href="/search">Find opportunities</Link><Link href="/tracker">Applications</Link><Link href="/cv" aria-current="page">CV studio</Link></nav>{message&&<p role="status" className="source-warning">{message}</p>}{loading?<p>Loading your studio…</p>:!signedIn?<section className="empty-state"><h2>Keep your career documents in your private workspace.</h2><Link href="/login" className="btn-primary">Log in</Link> <Link href="/signup" className="btn-outline">Create account</Link></section>:<>
 <div className="studio-grid"><section className="studio-panel"><h2>1. Your verified experience</h2><label className="upload-zone">Upload PDF, Word or text<input type="file" accept=".pdf,.docx,.txt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/><small>Up to 5 MB. Uploads are processed in memory and discarded.</small></label><label>Review and edit your CV text<textarea rows={15} value={text} onChange={e=>{setText(e.target.value);setConfirmed(false)}}/></label><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed this text and confirm it is accurate.</label><label className="checkbox-label"><input type="checkbox" checked={saveProfile} onChange={e=>setSaveProfile(e.target.checked)}/>Save this verified career profile to my account.</label><button className="text-action" onClick={async()=>{try{await accountRequest('profile',{method:'DELETE'});setMessage('Saved career profile deleted.')}catch(e){setMessage((e as Error).message)}}}>Delete my saved profile</button></section>
 <section className="studio-panel"><h2>2. The role you want</h2><label>Job title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Company<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Job description<textarea rows={14} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Paste the complete job description, or open CV tailoring from a job details page."/></label><div className="editor-actions"><button disabled={busy||!confirmed||text.length<30} onClick={()=>generate()} className="btn-primary">Improve and tailor CV</button><button disabled={busy||!confirmed||!title||text.length<30} onClick={()=>generate(true)} className="btn-outline">Draft cover letter</button></div><p className="field-help">Formatting and tailoring preserve your confirmed information. No skills, qualifications or achievements are invented.</p></section></div>
 {match&&<section className="match-panel"><h2>Requirements check</h2><div className="studio-grid"><div><h3>Evidence found</h3><p>{match.matched.join(', ')||'No recognised skill keywords matched.'}</p></div><div><h3>Not found in your CV</h3><p>{match.missing.join(', ')||'No missing recognised skill keywords.'}</p></div></div><p>{match.unassessed}</p></section>}
 {output&&<section className="studio-panel output-panel"><h2>3. Review your document</h2><textarea rows={20} value={output} onChange={e=>setOutput(e.target.value)}/><div className="editor-actions"><button disabled={busy} className="btn-primary" onClick={()=>download('pdf')}>Download PDF</button><button disabled={busy} className="btn-outline" onClick={()=>download('docx')}>Download Word</button><button className="text-action" onClick={()=>{setOutput('');setMatch(null)}}>Discard this document</button></div><p className="field-help">Generated documents stay in this page until you download or discard them. Your original upload is never stored.</p></section>}
 </>}</main><Footer/></>
}
