import "server-only";
import { XMLParser } from "fast-xml-parser";
import { API_URL } from "./api";
import { countries } from "./countries";
import { type Job,plain,eligible,matches } from "./jobs";
const names=Object.fromEntries(countries);
async function feed(url:string,seconds=21600){const r=await fetch(url,{next:{revalidate:seconds},signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error('Source unavailable');return r.json()}
async function opportunities(country:string):Promise<Job[]>{
 const r=await fetch('https://opportunitydesk.org/feed/',{next:{revalidate:21600},signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error('Feed unavailable');
 const data=new XMLParser({processEntities:false}).parse(await r.text());const items=data.rss?.channel?.item||[];
 return (Array.isArray(items)?items:[items]).filter((item:Record<string,unknown>)=>{const cats=(Array.isArray(item.category)?item.category:[item.category]).map(plain);return cats.some(c=>eligible(c,country)||c==='America'&&(['us','ca','mx'].includes(country))||c==='Australia and Oceania'&&eligible("oceania",country))}).map((item:Record<string,unknown>)=>{const url=plain(item.link);const description=plain(item.description);const deadlineText=description.match(/Deadline:\s*([A-Za-z]+ \d{1,2}, \d{4})/i)?.[1];const deadline=deadlineText?new Date(deadlineText+' 23:59:59 GMT').toISOString():null;return {id:`opportunity:${encodeURIComponent(url)}`,title:plain(item.title),company:'Provider listed at original source',location:'Regional listing. Verify country eligibility at source.',description:description+'\n\nThis is a publisher excerpt. Read the original opportunity for the provider, complete requirements and application instructions. Country eligibility must be confirmed there.',url,source:'Opportunity Desk',source_url:url,created:plain(item.pubDate),deadline,job_type:plain(item.title)};});
}
export async function searchJobs(p:URLSearchParams){const country=p.get('country')||'gh',page=Math.max(1,Math.min(10,Number(p.get('page'))||1));if(!names[country])return {jobs:[],errors:['Choose a valid country.']};
 const tasks:{name:string;task:Promise<Job[]>}[]=[];
 tasks.push({name:"Opportunity Desk",task:opportunities(country)});
 const backend=new URLSearchParams(p);backend.set('country',country);backend.set('page',String(page));backend.set('q',p.get('q')||'');
 tasks.push({name:'Himalayas / Adzuna',task:feed(`${API_URL}/search?${backend}`,300).then(d=>{if(d.errors?.length&&!(d.jobs?.length))throw new Error();return (d.jobs||[]).map((j:Job)=>({...j,company:j.company||'',location:j.location||'',description:plain(j.description)}))})});
 tasks.push({name:'Jobicy',task:feed('https://jobicy.com/api/v2/remote-jobs?count=200',3600).then(d=>(d.jobs||[]).filter((j:Record<string,unknown>)=>eligible(String(j.jobGeo||''),country)).map((j:Record<string,unknown>)=>({id:`jobicy:${j.id}`,title:plain(j.jobTitle),company:plain(j.companyName),location:plain(j.jobGeo),description:plain(j.jobDescription||j.jobExcerpt),url:plain(j.url),source:'Jobicy',source_url:plain(j.url),created:j.pubDate,remote:true,job_type:Array.isArray(j.jobType)?j.jobType.join(', '):plain(j.jobType),industry:Array.isArray(j.jobIndustry)?j.jobIndustry.join(', '):'',experience:plain(j.jobLevel),salary_min:j.salaryMin,salary_max:j.salaryMax,salary_currency:j.salaryCurrency,salary_period:j.salaryPeriod})) as Job[])});
 tasks.push({name:'Remotive',task:feed('https://remotive.com/api/remote-jobs').then(d=>(d.jobs||[]).filter((j:Record<string,unknown>)=>eligible(String(j.candidate_required_location||''),country)).map((j:Record<string,unknown>)=>({id:`remotive:${j.id}`,title:plain(j.title),company:plain(j.company_name),location:plain(j.candidate_required_location),description:plain(j.description),url:plain(j.url),source:'Remotive',source_url:plain(j.url),created:j.publication_date,remote:true,job_type:plain(j.job_type),industry:plain(j.category)})) as Job[])});
 if(['de','gb'].includes(country))tasks.push({name:'Arbeitnow',task:feed(`https://www.arbeitnow.${country==='gb'?'co.uk':'com'}/api/job-board-api?page=${page}`).then(d=>(d.data||[]).map((j:Record<string,unknown>)=>({id:`arbeitnow:${j.slug}`,title:plain(j.title),company:plain(j.company_name),location:plain(j.location),description:plain(j.description),url:plain(j.url),source:'Arbeitnow',source_url:plain(j.url),remote:Boolean(j.remote),job_type:Array.isArray(j.job_types)?j.job_types.join(', '):'',industry:Array.isArray(j.tags)?j.tags.join(', '):''})) as Job[])});
 // Public company career boards, queried as public postings only. More boards can be configured by the owner.
 const boards=(process.env.PUBLIC_SMARTRECRUITERS_BOARDS||'AmaliTech,WACSI,Sumundi,DevelopersInVogue,JobsForHumanity').split(',').filter(b=>/^[a-zA-Z0-9-]{1,80}$/.test(b)).slice(0,15);
 for(const board of boards)tasks.push({name:board,task:feed(`https://api.smartrecruiters.com/v1/companies/${board}/postings?limit=100&destination=PUBLIC&country=${country}`,21600).then(d=>(d.content||[]).filter((j:Record<string,unknown>)=>(j.location as Record<string,string>)?.country?.toLowerCase()===country).map((j:Record<string,unknown>)=>({id:`smart:${board}:${j.id}`,title:plain(j.name),company:board,location:plain((j.location as Record<string,string>)?.city),description:'Open this role to load the employer’s full posting.',url:`https://jobs.smartrecruiters.com/${board}/${j.id}`,source:board,source_url:`https://careers.smartrecruiters.com/${board}`,remote:Boolean((j.location as Record<string,unknown>)?.remote),job_type:plain((j.typeOfEmployment as Record<string,string>)?.label),experience:plain((j.experienceLevel as Record<string,string>)?.label),industry:plain((j.industry as Record<string,string>)?.label)})) as Job[])});
 const results=await Promise.allSettled(tasks.map(t=>t.task));const jobs:Job[]=[],errors:string[]=[];const seen=new Set<string>();for(let i=0;i<results.length;i++){const r=results[i];if(r.status==='rejected'){errors.push(tasks[i].name);continue}const filtered=r.value.filter(j=>matches(j,p));const slice=tasks[i].name==='Himalayas / Adzuna'||tasks[i].name==='Arbeitnow'?filtered:filtered.slice((page-1)*20,page*20);for(const j of slice){const key=`${j.company.toLowerCase()}|${j.title.toLowerCase()}|${j.location.toLowerCase()}`;if(!seen.has(key)){seen.add(key);jobs.push(j)}}}return {jobs,errors,page};
}
export async function getJob(id:string,p:URLSearchParams):Promise<Job|undefined>{
 if(/^smart:[a-zA-Z0-9-]+:[a-zA-Z0-9-]+$/.test(id)){const [,board,posting]=id.split(':');const boards=(process.env.PUBLIC_SMARTRECRUITERS_BOARDS||'AmaliTech,WACSI,Sumundi,DevelopersInVogue,JobsForHumanity').split(',');if(!boards.includes(board))return;const d=await feed(`https://api.smartrecruiters.com/v1/companies/${board}/postings/${posting}`,3600);const description=Object.values(d.jobAd?.sections||{}).map((s)=>plain((s as {text?:string}).text)).join('\n\n');return {id,title:plain(d.name),company:plain(d.company?.name)||board,location:plain(d.location?.city),description,url:d.applyUrl||`https://jobs.smartrecruiters.com/${board}/${posting}`,source:board,source_url:d.ref||`https://careers.smartrecruiters.com/${board}`,remote:Boolean(d.location?.remote),job_type:plain(d.typeOfEmployment?.label),industry:plain(d.industry?.label)};}
 return (await searchJobs(p)).jobs.find(j=>j.id===id);
}
