import { countries } from "./countries";
export type Job={id:string;title:string;company:string;location:string;description:string;url:string;source:string;source_url?:string;created?:string|number;deadline?:string|number|null;salary_min?:number|null;salary_max?:number|null;salary_currency?:string;salary_period?:string;remote?:boolean;job_type?:string;industry?:string;experience?:string};
export const listingTypes=[['all','All listings'],['permanent','Permanent'],['part-time','Part-time'],['internship','Internships'],['graduate','Graduate roles'],['apprenticeship','Apprenticeships'],['contract','Contracts'],['scholarship','Scholarships']];
export function plain(value:unknown):string{return typeof value==='string'?value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<\/(p|div|li|h[1-6])>|<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/&#0?39;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(0x10ffff,Number(n)))).trim():''}
const names=Object.fromEntries(countries);
const regions:Record<string,string[]>={africa:'dz ao bj bw bf bi cv cm cf td km cg cd ci dj eg gq er sz et ga gm gh gn gw ke ls lr ly mg mw ml mr mu ma mz na ne ng rw st sn sc sl so za ss sd tz tg tn ug zm zw'.split(' '),europe:'al ad at by be ba bg hr cy cz dk ee fi fr de gr hu is ie it lv li lt lu mt md mc me nl mk no pl pt ro ru sm rs sk si es se ch tr ua gb va'.split(' '),'north america':'us ca mx'.split(' '),asia:'af am az bh bd bt bn kh cn ge in id ir iq il jp jo kz kp kr kw kg la lb my mv mn mm np om pk ps ph qa sa sg lk sy tw tj th tl tm ae uz vn ye'.split(' '),oceania:'au nz fj pg ws sb to vu'.split(' ')};
export function eligible(geo:string,country:string){const parts=plain(geo).toLowerCase().split(/[,;|]/).map(x=>x.trim());const aliases=[country,names[country]?.toLowerCase(),country==='us'?'usa':country==='gb'?'uk':''].filter(Boolean);return parts.some(p=>['worldwide','anywhere','global'].includes(p)||aliases.includes(p)||regions[p]?.includes(country)||(p==='emea'&&(regions.europe.includes(country)||regions.africa.includes(country)||'bh ir iq il jo kw lb om ps qa sa sy ae ye'.split(' ').includes(country)))||(p==='apac'&&(regions.asia.includes(country)||regions.oceania.includes(country)))||(p==='eu'&&'at be bg hr cy cz dk ee fi fr de gr hu ie it lv lt lu mt nl pl pt ro sk si es se'.split(' ').includes(country)))}
function safe(job:Job){return Boolean(job.title&&/^https?:\/\//i.test(job.url));}
export function matches(job:Job,p:URLSearchParams){const q=(p.get('q')||'').toLowerCase().trim();if(q&&!q.split(/\s+/).every(w=>`${job.title} ${job.company} ${job.description}`.toLowerCase().includes(w)))return false;if(p.get('remote')==='true'&&!job.remote)return false;
 const type=p.get('job_type')||'all',content=`${job.title} ${job.job_type||''}`.toLowerCase();const patterns:Record<string,RegExp>={'permanent':/full.?time|permanent/,'part-time':/part.?time/,'internship':/intern/,'graduate':/graduate|entry.level/,'apprenticeship':/apprentice/,'contract':/contract|freelance/,'scholarship':/scholarship|bursary|fellowship/};if(type!=='all'&&patterns[type]&&!patterns[type].test(content))return false;
 const industry=p.get('industry');if(industry&&!`${job.industry||''} ${job.title} ${job.description}`.toLowerCase().includes(industry.toLowerCase()))return false;
 const experience=p.get('experience');if(experience){const terms:Record<string,RegExp>={entry:/entry.level|junior|graduate|intern/,mid:/mid.level|intermediate/,senior:/senior|lead|principal/,manager:/manager|director/};if(terms[experience]&&!terms[experience].test(`${job.experience||''} ${job.title} ${job.description}`.toLowerCase()))return false}
 const minimum=Number(p.get('salary_min')||0);if(minimum){if(job.salary_min==null||Number(job.salary_min)<minimum||job.salary_currency!==p.get('currency')||job.salary_period!==p.get('salary_period'))return false}
 if(job.deadline){const expiry=typeof job.deadline==='number'?job.deadline*1000:Date.parse(job.deadline);if(Number.isFinite(expiry)&&expiry<Date.now())return false}
 return safe(job);
}
